app: rag-router
partOf: rag-base

# namespace: rag-base
# createNamespace: true

argocdNamespace: openshift-gitops

baseImage:
  version: "3.11"
  name: "registry.access.redhat.com/ubi9/python-311"
  tag: "9.6"

workingDir: /app

vcs:
  uri: https://github.com/alpha-hack-program/rag-router.git
  ref: main
  name: alpha-hack-program/rag-router
  path: .
  # sourceSecret: git-pat-bc-secret

mountCaCerts: "false"

embeddingsDefaultModel: multilingual-e5-large-gpu

embeddings:
  - name: multilingual-e5-large-gpu
    url: http://multilingual-e5-large-gpu-predictor:8080
    model: multilingual-e5-large-gpu
    api_key: ""

models:
  - name: granite-3-1-8b
    url: http://granite-3-1-8b-instruct-predictor:8080
    model: granite-3-1-8b-instruct
    api_key: ""
  - name: mistral-7b-instruct-v0-3
    url: https://mistral-7b-instruct-v0-3-predictor:8080
    model: mistral-7b-instruct
    api_key: ""
  - name: llama-3-1-8b
    url: https://llama-3-1-8b-instruct-predictor:8080
    model: meta-llama/Llama-3.1-8B-Instruct
    api_key: ""

prompts:
  - name: context
    description: "Prompt for answering general questions with context"
    template: |
      Given the following context:
      <context>
      {context}
      </context>

      Answer the question: {query}
      Don't use any information outside the context provided. Don't make up any information. If you don't know the answer, just say 'I don't know'.

  - name: default
    description: "Prompt for answering questions without context"
    template: |
      Answer the question: {query}
      Don't use any context. Don't make up any information. If you don't know the answer, just say 'I don't know'.
  
milvus:
  name: milvus
  username: root
  password: Milvus
  port: '19530'
  host: vectordb-milvus
  database: default
  collectionName: document_chunks