apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.app }}-{{ .Values.webuiApplication.name }}"
  namespace: {{ .Values.argocdNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.dataScienceProjectNamespace }}
  source:
    repoURL: 'https://helm.openwebui.com'
    targetRevision: 3.8.0
    chart: open-webui
    helm:
      values: |
      
        ollama:
          enabled: false

        pipelines:
          enabled: false

        tika:
          enabled: false

        persistence:
          enabled: true
          size: 2Gi
          accessModes:
            - ReadWriteOnce

        extraEnvVars:
          - name: ENABLE_SIGNUP
            value: "true"
          - name: ENABLE_LOGIN_FORM
            value: "true"
          - name: ADMIN_EMAIL
            value: "admin@acme.com"

          # Connect to OpenAI-compatible backend
          - name: ENABLE_OPENAI_API
            value: "true"
          - name: OPENAI_API_BASE_URL
            value: "http://{{ .Values.routerApplication.name }}:7777/v1"
          - name: OPENAI_API_KEY
            value: "{{ .Values.webuiApplication.openaiApiKey }}"

          # # Prevent SQLite crash by pointing to a writable dummy location
          # - name: DATABASE_URL
          #   value: "sqlite:////tmp/open-webui.db"


          # Required for app startup
          - name: WEBUI_SECRET_KEY
            value: "{{ .Values.webuiApplication.secretKey }}"

          # Optional: disable web search
          - name: ENABLE_RAG_WEB_SEARCH
            value: "false"

  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
